/* MakanMate listings data — 15 onboarded PGs (Baner / Balewadi / Pashan / Hinjewadi, Pune) */
const MM = {
  listings: [
    {
      id:"sg", type:"pg", typeLabel:"PG",
      title:"Sadguru PG Services for Girls",
      area:"Baner, Pune", address:"Baner, Pune 411045",
      lat:18.5612, lng:73.7891,
      rent:10500, rentUnit:"/ bed / month", deposit:21000, maintenance:0,
      photos:["pg_sadguru_1","pg_sadguru_2","pg_sadguru_3","pg_sadguru_4"],
      photoLabels:["Common area","Room","Room view","Facilities"],
      safety:8.8, match:0, rating:4.5, reviewCount:0,
      busMin:35, scootyMin:22, cabMin:20,
      available:"Now", hasTour:false,
      amenities:["Wi-Fi","CCTV & security","Hot water","Power backup","Laundry","Daily housekeeping"],
      rules:["Women only","Visitors in lobby only","Gate closes at 10 pm"],
      tags:["Women only","Baner","CCTV"],
      owner:{name:"Sadguru PG",initials:"SP",replyTime:"~30 min",phone:"919363515052",since:"2024"},
      nearby:[{label:"Bus stop",dist:"300 m"},{label:"Grocery",dist:"200 m"},{label:"Hospital",dist:"1.5 km"},{label:"Cafés",dist:"Nearby"}],
      reasons:[{good:true,text:"Women only — safe & secure"},{good:true,text:"CCTV & 24×7 security"},{good:true,text:"Baner — well connected"},{good:false,text:"4 photos available currently"}],
      reviews:[],
      flat:null,
    },
    {
      id:"kp", type:"pg", typeLabel:"PG",
      title:"Krishna PG Service",
      area:"Baner, Pune", address:"Baner, Pune 411045",
      lat:18.5575, lng:73.7855,
      rent:9000, rentUnit:"/ bed / month", deposit:18000, maintenance:0,
      photos:["pg_krishna_1","pg_krishna_2","pg_krishna_3","pg_krishna_4","pg_krishna_5","pg_krishna_6","pg_krishna_7","pg_krishna_8","pg_krishna_9","pg_krishna_10"],
      photoLabels:["Entrance","Common room","Twin room","Single room","Kitchen","Bathroom","Corridor","Study area","Parking","Exterior"],
      safety:8.6, match:0, rating:4.4, reviewCount:0,
      busMin:35, scootyMin:22, cabMin:20,
      available:"Now", hasTour:false,
      amenities:["Wi-Fi","Hot water","Power backup","CCTV","Laundry","Study table & chair"],
      rules:["Unisex","CCTV & security","Gate closes at 11 pm"],
      tags:["Unisex","Baner","Wi-Fi"],
      owner:{name:"Krishna PG",initials:"KP",replyTime:"~30 min",phone:"918180805118",since:"2024"},
      nearby:[{label:"Bus stop",dist:"350 m"},{label:"Grocery",dist:"250 m"},{label:"Hospital",dist:"1.8 km"},{label:"Cafés",dist:"Nearby"}],
      reasons:[{good:true,text:"Unisex — open to all"},{good:true,text:"10 photos to browse"},{good:true,text:"Baner — near IT hubs"},{good:false,text:"Contact owner for room options"}],
      reviews:[],
      flat:null,
    },
    {
      id:"dt", type:"pg", typeLabel:"PG",
      title:"DownTown PG",
      area:"Baner, Pune", address:"Baner, Pune 411045",
      lat:18.5601, lng:73.7910,
      rent:9500, rentUnit:"/ bed / month", deposit:19000, maintenance:0,
      photos:["pg_downtown_1","pg_downtown_2","pg_downtown_3","pg_downtown_4","pg_downtown_5","pg_downtown_6","pg_downtown_7","pg_downtown_8","pg_downtown_9","pg_downtown_10","pg_downtown_11","pg_downtown_12","pg_downtown_13","pg_downtown_14","pg_downtown_15","pg_downtown_16","pg_downtown_17","pg_downtown_18","pg_downtown_19","pg_downtown_20","pg_downtown_21","pg_downtown_22","pg_downtown_23","pg_downtown_24","pg_downtown_25","pg_downtown_26","pg_downtown_27","pg_downtown_28","pg_downtown_29","pg_downtown_30","pg_downtown_31","pg_downtown_32"],
      photoLabels:["Entrance","Reception","Common room","Twin room","Single room","Room view 2","Room view 3","Wardrobe","Balcony","Kitchen","Kitchen 2","Dining area","Bathroom","Bathroom 2","Corridor","Study area","Terrace","Terrace view","Parking","Generator","Water storage","Security desk","Side entrance","Garden","Common hall","Notice board","Laundry","Staff room","Back lane","Exterior front","Exterior side","Exterior night"],
      safety:8.7, match:0, rating:4.5, reviewCount:0,
      busMin:35, scootyMin:22, cabMin:20,
      available:"Now", hasTour:false,
      amenities:["Wi-Fi","Hot water","Power backup","CCTV & security","Laundry","Meals available","Parking","Study table & chair"],
      rules:["Boys only","No alcohol on premises","Gate closes at 11 pm","Visitors in lobby"],
      tags:["Boys only","Baner","Meals available"],
      owner:{name:"DownTown PG",initials:"DP",replyTime:"~30 min",phone:"917766986677",since:"2024"},
      nearby:[{label:"Bus stop",dist:"300 m"},{label:"Grocery",dist:"200 m"},{label:"Hospital",dist:"1.6 km"},{label:"IT parks",dist:"~25 min"}],
      reasons:[{good:true,text:"32 photos — full transparency"},{good:true,text:"Boys only — dedicated space"},{good:true,text:"Meals & parking available"},{good:false,text:"Contact owner for vacancy"}],
      reviews:[],
      flat:null,
    },
    {
      id:"si", type:"pg", typeLabel:"PG",
      title:"SKY Inn PG Services",
      area:"Balewadi, Baner, Pune", address:"Balewadi, Pune 411045",
      lat:18.5779, lng:73.7720,
      rent:10000, rentUnit:"/ bed / month", deposit:20000, maintenance:0,
      photos:["pg_skyinn_1","pg_skyinn_2","pg_skyinn_3","pg_skyinn_4","pg_skyinn_5","pg_skyinn_6","pg_skyinn_7","pg_skyinn_8","pg_skyinn_9","pg_skyinn_10","pg_skyinn_11","pg_skyinn_12","pg_skyinn_13","pg_skyinn_14","pg_skyinn_15","pg_skyinn_16","pg_skyinn_17","pg_skyinn_18"],
      photoLabels:["Entrance","Lobby","Common area","Twin room","Single room","Room detail","Wardrobe","Kitchen","Dining area","Bathroom","Corridor","Terrace","Parking","Exterior front","Exterior side","Garden","Security","Common hall"],
      safety:8.5, match:0, rating:4.3, reviewCount:0,
      busMin:30, scootyMin:18, cabMin:16,
      available:"Now", hasTour:false,
      amenities:["Wi-Fi","Hot water","Power backup","CCTV","Laundry","Study table & chair","Parking"],
      rules:["CCTV & security","Gate closes at 11 pm","Visitors in lobby"],
      tags:["Balewadi","Wi-Fi","Parking"],
      owner:{name:"SKY Inn PG",initials:"SI",replyTime:"~30 min",phone:"919112233977",since:"2024"},
      nearby:[{label:"Bus stop",dist:"400 m"},{label:"Grocery",dist:"300 m"},{label:"Hospital",dist:"1.5 km"},{label:"Balewadi High St",dist:"1 km"}],
      reasons:[{good:true,text:"Balewadi — near Baner & Hinjewadi"},{good:true,text:"18 photos available"},{good:true,text:"Parking available"},{good:false,text:"Contact owner for gender preference"}],
      reviews:[],
      flat:null,
    },
    {
      id:"sl", type:"pg", typeLabel:"PG",
      title:"Sri Lakshmi Luxury PG",
      area:"Pashan, Baner, Pune", address:"Pashan, Pune 411021",
      lat:18.5410, lng:73.8058,
      rent:12000, rentUnit:"/ bed / month", deposit:24000, maintenance:0,
      photos:["pg_srilakshmi_1","pg_srilakshmi_2","pg_srilakshmi_3","pg_srilakshmi_4","pg_srilakshmi_5","pg_srilakshmi_6","pg_srilakshmi_7","pg_srilakshmi_8","pg_srilakshmi_9","pg_srilakshmi_10","pg_srilakshmi_11","pg_srilakshmi_12","pg_srilakshmi_13","pg_srilakshmi_14"],
      photoLabels:["Lobby","Common area","Deluxe room","Standard room","Room detail","Wardrobe","Kitchen","Dining","Bathroom","Corridor","Terrace","Parking","Exterior front","Building"],
      safety:9.0, match:0, rating:4.6, reviewCount:0,
      busMin:28, scootyMin:16, cabMin:14,
      available:"Now", hasTour:false,
      amenities:["Wi-Fi (50 Mbps)","Hot water","Power backup","CCTV & security","Laundry","Daily housekeeping","Meals available","AC rooms available","Parking"],
      rules:["CCTV & security","Gate closes at 11 pm","Visitors in lobby"],
      tags:["Luxury","Pashan","AC rooms"],
      owner:{name:"Sri Lakshmi PG",initials:"SL",replyTime:"~20 min",phone:"919112488666",since:"2024"},
      nearby:[{label:"Bus stop",dist:"250 m"},{label:"Grocery",dist:"200 m"},{label:"Hospital",dist:"1 km"},{label:"Pashan Lake",dist:"500 m"}],
      reasons:[{good:true,text:"Luxury PG — AC rooms available"},{good:true,text:"Daily housekeeping & meals"},{good:true,text:"Near Pashan & Baner"},{good:false,text:"Premium pricing — ₹12,000/bed"}],
      reviews:[],
      flat:null,
    },
    {
      id:"iu", type:"pg", typeLabel:"PG",
      title:"Indweller Stay — Ujwal Regalia",
      area:"Baner, Pune", address:"Baner, Pune 411045",
      lat:18.5618, lng:73.7878,
      rent:11000, rentUnit:"/ bed / month", deposit:22000, maintenance:0,
      photos:["pg_indweller_ujwal_1","pg_indweller_ujwal_2","pg_indweller_ujwal_3","pg_indweller_ujwal_4","pg_indweller_ujwal_5","pg_indweller_ujwal_6","pg_indweller_ujwal_7","pg_indweller_ujwal_8","pg_indweller_ujwal_9","pg_indweller_ujwal_10"],
      photoLabels:["Lobby","Common room","Twin room","Single room","Wardrobe","Kitchen","Dining","Bathroom","Corridor","Exterior"],
      safety:8.7, match:0, rating:4.4, reviewCount:0,
      busMin:35, scootyMin:22, cabMin:20,
      available:"Now", hasTour:false,
      amenities:["Wi-Fi","Hot water","Power backup","CCTV & security","Laundry","Meals available","Study table & chair"],
      rules:["CCTV & security","Gate closes at 11 pm","Visitors in lobby"],
      tags:["Indweller Stay","Baner","Meals available"],
      owner:{name:"Indweller Stay",initials:"IS",replyTime:"~30 min",phone:"919529043356",since:"2024"},
      nearby:[{label:"Bus stop",dist:"300 m"},{label:"Grocery",dist:"250 m"},{label:"Hospital",dist:"1.5 km"},{label:"IT parks",dist:"~22 min"}],
      reasons:[{good:true,text:"Indweller Stay — managed chain"},{good:true,text:"Meals & laundry included"},{good:true,text:"Baner — central location"},{good:false,text:"Contact owner for availability"}],
      reviews:[],
      flat:null,
    },
    {
      id:"im", type:"pg", typeLabel:"PG",
      title:"Indweller Stay — Mitrangan PG",
      area:"Baner, Pune", address:"Baner, Pune 411045",
      lat:18.5583, lng:73.7845,
      rent:9500, rentUnit:"/ bed / month", deposit:19000, maintenance:0,
      photos:["pg_indweller_mitrangan_1","pg_indweller_mitrangan_2","pg_indweller_mitrangan_3","pg_indweller_mitrangan_4","pg_indweller_mitrangan_5","pg_indweller_mitrangan_6"],
      photoLabels:["Entrance","Common area","Room","Kitchen","Bathroom","Exterior"],
      safety:8.5, match:0, rating:4.3, reviewCount:0,
      busMin:35, scootyMin:22, cabMin:20,
      available:"Now", hasTour:false,
      amenities:["Wi-Fi","Hot water","Power backup","CCTV","Laundry","Study table & chair"],
      rules:["CCTV & security","Gate closes at 11 pm","Visitors in lobby"],
      tags:["Indweller Stay","Baner","Wi-Fi"],
      owner:{name:"Indweller Stay",initials:"IS",replyTime:"~30 min",phone:"919529043356",since:"2024"},
      nearby:[{label:"Bus stop",dist:"350 m"},{label:"Grocery",dist:"300 m"},{label:"Hospital",dist:"1.6 km"},{label:"IT parks",dist:"~22 min"}],
      reasons:[{good:true,text:"Indweller Stay managed property"},{good:true,text:"Baner — near tech parks"},{good:true,text:"Affordable at ₹9,500/bed"},{good:false,text:"6 photos available currently"}],
      reviews:[],
      flat:null,
    },
    {
      id:"ht", type:"pg", typeLabel:"PG",
      title:"Hometown Premium PG 5",
      area:"Hinjewadi, Pune", address:"Hinjewadi, Pune 411057",
      lat:18.5855, lng:73.7050,
      rent:11000, rentUnit:"/ bed / month", deposit:22000, maintenance:0,
      photos:["pg_hometown_1","pg_hometown_2","pg_hometown_3","pg_hometown_4","pg_hometown_5","pg_hometown_6","pg_hometown_7","pg_hometown_8","pg_hometown_9","pg_hometown_10"],
      photoLabels:["Common area","Twin room","Single room","Wardrobe","Kitchen","Dining","Bathroom","Corridor","Terrace","Exterior"],
      safety:8.9, match:0, rating:4.5, reviewCount:0,
      busMin:15, scootyMin:8, cabMin:8,
      available:"Now", hasTour:false,
      amenities:["Wi-Fi","Hot water","Power backup","CCTV & security","Laundry","Daily housekeeping","Meals available"],
      rules:["Women only","CCTV & security","Gate closes at 10 pm","Visitors in lobby"],
      tags:["Women only","Hinjewadi","Near IT park"],
      owner:{name:"Hometown PG",initials:"HP",replyTime:"~20 min",phone:"918698198073",since:"2024"},
      nearby:[{label:"Hinjewadi IT park",dist:"~1 km"},{label:"Bus stop",dist:"400 m"},{label:"Grocery",dist:"300 m"},{label:"Hospital",dist:"1.2 km"}],
      reasons:[{good:true,text:"Walk to Hinjewadi IT park"},{good:true,text:"Women only — safe stay"},{good:true,text:"Meals & housekeeping included"},{good:false,text:"Owner has 4–5 more PGs — ask"}],
      reviews:[],
      flat:null,
    },
    {
      id:"ib", type:"pg", typeLabel:"PG",
      title:"Indweller Stay — B9 PG",
      area:"Baner, Pune", address:"Baner, Pune 411045",
      lat:18.5596, lng:73.7862,
      rent:9500, rentUnit:"/ bed / month", deposit:19000, maintenance:0,
      photos:["pg_indweller_b9_1","pg_indweller_b9_2","pg_indweller_b9_3","pg_indweller_b9_4","pg_indweller_b9_5","pg_indweller_b9_6","pg_indweller_b9_7","pg_indweller_b9_8","pg_indweller_b9_9","pg_indweller_b9_10","pg_indweller_b9_11","pg_indweller_b9_12","pg_indweller_b9_13","pg_indweller_b9_14","pg_indweller_b9_15"],
      photoLabels:["Entrance","Lobby","Common area","Twin room","Single room","Room detail","Wardrobe","Kitchen","Dining","Bathroom","Bathroom 2","Corridor","Study area","Terrace","Parking"],
      safety:8.6, match:0, rating:4.3, reviewCount:0,
      busMin:35, scootyMin:22, cabMin:20,
      available:"Now", hasTour:true,
      amenities:["Wi-Fi","Hot water","Power backup","CCTV","Laundry","Meals available","Parking"],
      rules:["CCTV & security","Gate closes at 11 pm","Visitors in lobby"],
      tags:["Indweller Stay","Baner","16 photos"],
      owner:{name:"Indweller Stay",initials:"IS",replyTime:"~30 min",phone:"917972382077",since:"2024"},
      nearby:[{label:"Bus stop",dist:"300 m"},{label:"Grocery",dist:"250 m"},{label:"Hospital",dist:"1.5 km"},{label:"IT parks",dist:"~22 min"}],
      reasons:[{good:true,text:"Indweller Stay managed property"},{good:true,text:"16 photos — see every corner"},{good:true,text:"Meals & parking available"},{good:false,text:"Contact for current vacancy"}],
      reviews:[],
      flat:null,
    },
    {
      id:"ih", type:"pg", typeLabel:"PG",
      title:"Indweller Stay — House PG",
      area:"Baner, Pune", address:"Baner, Pune 411045",
      lat:18.5570, lng:73.7880,
      rent:9000, rentUnit:"/ bed / month", deposit:18000, maintenance:0,
      photos:["pg_indweller_house_1","pg_indweller_house_2","pg_indweller_house_3","pg_indweller_house_4","pg_indweller_house_5","pg_indweller_house_6","pg_indweller_house_7","pg_indweller_house_8"],
      photoLabels:["Common area","Room","Room view","Kitchen","Bathroom","Corridor","Exterior front","Exterior side"],
      safety:8.4, match:0, rating:4.2, reviewCount:0,
      busMin:35, scootyMin:22, cabMin:20,
      available:"Now", hasTour:false,
      amenities:["Wi-Fi","Hot water","Power backup","CCTV","Laundry"],
      rules:["CCTV & security","Gate closes at 11 pm","Visitors in lobby"],
      tags:["Indweller Stay","Baner","Affordable"],
      owner:{name:"Indweller Stay",initials:"IS",replyTime:"~30 min",phone:"917972382077",since:"2024"},
      nearby:[{label:"Bus stop",dist:"350 m"},{label:"Grocery",dist:"300 m"},{label:"Hospital",dist:"1.8 km"},{label:"IT parks",dist:"~22 min"}],
      reasons:[{good:true,text:"Indweller Stay managed property"},{good:true,text:"Affordable at ₹9,000/bed"},{good:true,text:"Baner — central location"},{good:false,text:"Limited vacancy — contact soon"}],
      reviews:[],
      flat:null,
    },
    {
      id:"sv", type:"pg", typeLabel:"PG",
      title:"Sri Vigneswara PG Services",
      area:"Baner, Pune", address:"Baner, Pune 411045",
      lat:18.5605, lng:73.7900,
      rent:9000, rentUnit:"/ bed / month", deposit:18000, maintenance:0,
      photos:["pg_srivigneswara_1","pg_srivigneswara_2","pg_srivigneswara_3","pg_srivigneswara_4","pg_srivigneswara_5","pg_srivigneswara_6","pg_srivigneswara_7","pg_srivigneswara_8","pg_srivigneswara_9","pg_srivigneswara_10"],
      photoLabels:["Entrance","Common room","Twin room","Single room","Kitchen","Bathroom","Study area","Corridor","Terrace","Exterior"],
      safety:8.5, match:0, rating:4.3, reviewCount:0,
      busMin:35, scootyMin:22, cabMin:20,
      available:"Now", hasTour:false,
      amenities:["Wi-Fi","Hot water","Power backup","CCTV & security","Laundry","Study table & chair","Meals available"],
      rules:["Boys only","No alcohol on premises","Gate closes at 11 pm","Visitors in lobby"],
      tags:["Boys only","Baner","Meals available"],
      owner:{name:"Sri Vigneswara PG",initials:"SV",replyTime:"~30 min",phone:"917768909000",since:"2024"},
      nearby:[{label:"Bus stop",dist:"300 m"},{label:"Grocery",dist:"200 m"},{label:"Hospital",dist:"1.5 km"},{label:"IT parks",dist:"~22 min"}],
      reasons:[{good:true,text:"Boys only — dedicated space"},{good:true,text:"Meals & study area included"},{good:true,text:"Owner has 2 more PGs"},{good:false,text:"Post paint work — contact for status"}],
      reviews:[],
      flat:null,
    },
    {
      id:"7h", type:"pg", typeLabel:"PG",
      title:"7 Hills PG",
      area:"Baner, Pune", address:"Baner, Pune 411045",
      lat:18.5588, lng:73.7835,
      rent:8500, rentUnit:"/ bed / month", deposit:17000, maintenance:0,
      photos:["pg_7hills_1","pg_7hills_2","pg_7hills_3","pg_7hills_4","pg_7hills_5","pg_7hills_6","pg_7hills_7"],
      photoLabels:["Entrance","Common area","Room","Kitchen","Bathroom","Corridor","Exterior"],
      safety:8.4, match:0, rating:4.2, reviewCount:0,
      busMin:35, scootyMin:22, cabMin:20,
      available:"Now", hasTour:false,
      amenities:["Wi-Fi","Hot water","Power backup","CCTV","Laundry"],
      rules:["Boys only","Gate closes at 11 pm","Visitors in lobby"],
      tags:["Boys only","Baner","Budget-friendly"],
      owner:{name:"7 Hills PG",initials:"7H",replyTime:"~30 min",phone:"918799852093",since:"2024"},
      nearby:[{label:"Bus stop",dist:"400 m"},{label:"Grocery",dist:"300 m"},{label:"Hospital",dist:"1.8 km"},{label:"IT parks",dist:"~22 min"}],
      reasons:[{good:true,text:"Budget-friendly at ₹8,500/bed"},{good:true,text:"Boys only — Baner"},{good:true,text:"Wi-Fi & power backup"},{good:false,text:"7 photos available currently"}],
      reviews:[],
      flat:null,
    },
    {
      id:"el", type:"pg", typeLabel:"PG",
      title:"Elegance PG Services",
      area:"Baner, Pune", address:"Baner, Pune 411045",
      lat:18.5625, lng:73.7895,
      rent:10000, rentUnit:"/ bed / month", deposit:20000, maintenance:0,
      photos:["pg_elegance_1","pg_elegance_2","pg_elegance_3","pg_elegance_4","pg_elegance_5","pg_elegance_6","pg_elegance_7","pg_elegance_8","pg_elegance_9","pg_elegance_10","pg_elegance_11","pg_elegance_12"],
      photoLabels:["Entrance","Lobby","Common area","Twin room","Single room","Room detail","Kitchen","Dining","Bathroom","Corridor","Terrace","Exterior"],
      safety:8.6, match:0, rating:4.4, reviewCount:0,
      busMin:35, scootyMin:22, cabMin:20,
      available:"Now", hasTour:false,
      amenities:["Wi-Fi","Hot water","Power backup","CCTV & security","Laundry","Meals available","Study table & chair"],
      rules:["CCTV & security","Gate closes at 11 pm","Visitors in lobby"],
      tags:["Baner","Meals available","12 photos"],
      owner:{name:"Elegance PG",initials:"EP",replyTime:"~30 min",phone:"919545678919",since:"2024"},
      nearby:[{label:"Bus stop",dist:"300 m"},{label:"Grocery",dist:"200 m"},{label:"Hospital",dist:"1.5 km"},{label:"IT parks",dist:"~22 min"}],
      reasons:[{good:true,text:"Elegantly maintained — 12 photos"},{good:true,text:"Meals & study area included"},{good:true,text:"Baner — prime location"},{good:false,text:"Contact owner for gender preference"}],
      reviews:[],
      flat:null,
    },
    {
      id:"ti", type:"pg", typeLabel:"PG",
      title:"Tirumala PG",
      area:"Baner, Pune", address:"Baner, Pune 411045",
      lat:18.5558, lng:73.7852,
      rent:9000, rentUnit:"/ bed / month", deposit:18000, maintenance:0,
      photos:["pg_tirumala_1","pg_tirumala_2","pg_tirumala_3","pg_tirumala_4","pg_tirumala_5","pg_tirumala_6","pg_tirumala_7","pg_tirumala_8","pg_tirumala_9","pg_tirumala_10","pg_tirumala_11","pg_tirumala_12","pg_tirumala_13"],
      photoLabels:["Entrance","Common area","Twin room","Single room","Room detail","Wardrobe","Kitchen","Dining","Bathroom","Corridor","Terrace","Parking","Exterior"],
      safety:8.5, match:0, rating:4.3, reviewCount:0,
      busMin:35, scootyMin:22, cabMin:20,
      available:"Now", hasTour:false,
      amenities:["Wi-Fi","Hot water","Power backup","CCTV","Laundry","Meals available","Parking"],
      rules:["Boys only","No alcohol on premises","Gate closes at 11 pm","Visitors in lobby"],
      tags:["Boys only","Baner","Meals available"],
      owner:{name:"Tirumala PG",initials:"TP",replyTime:"~30 min",phone:"916301025352",since:"2024"},
      nearby:[{label:"Bus stop",dist:"350 m"},{label:"Grocery",dist:"250 m"},{label:"Hospital",dist:"1.6 km"},{label:"IT parks",dist:"~22 min"}],
      reasons:[{good:true,text:"Boys only — well maintained"},{good:true,text:"13 photos — transparent listing"},{good:true,text:"Meals & parking available"},{good:false,text:"Contact owner for room types"}],
      reviews:[],
      flat:null,
    },
    {
      id:"lv", type:"pg", typeLabel:"PG",
      title:"Lovely PG Services for Girls",
      area:"Baner, Pune", address:"Baner, Pune 411045",
      lat:18.5635, lng:73.7870,
      rent:10500, rentUnit:"/ bed / month", deposit:21000, maintenance:0,
      photos:["pg_lovely_1","pg_lovely_2","pg_lovely_3","pg_lovely_4","pg_lovely_5","pg_lovely_6","pg_lovely_7","pg_lovely_8"],
      photoLabels:["Common area","Twin room","Single room","Wardrobe","Kitchen","Bathroom","Corridor","Exterior"],
      safety:8.9, match:0, rating:4.5, reviewCount:0,
      busMin:35, scootyMin:22, cabMin:20,
      available:"Now", hasTour:false,
      amenities:["Wi-Fi","Hot water","Power backup","CCTV & security","Laundry","Daily housekeeping","Meals available"],
      rules:["Women only","CCTV & security","Gate closes at 10 pm","Visitors in lobby"],
      tags:["Women only","Baner","Meals available"],
      owner:{name:"Lovely PG",initials:"LP",replyTime:"~30 min",phone:"918623839149",since:"2024"},
      nearby:[{label:"Bus stop",dist:"300 m"},{label:"Grocery",dist:"200 m"},{label:"Hospital",dist:"1.5 km"},{label:"IT parks",dist:"~22 min"}],
      reasons:[{good:true,text:"Women only — safe & homely"},{good:true,text:"Meals & housekeeping included"},{good:true,text:"CCTV & gate security"},{good:false,text:"Contact owner for vacancy"}],
      reviews:[],
      flat:null,
    },
  ],

  fmt(n){ return "₹" + n.toLocaleString("en-IN"); },
  moveIn(l){ return l.rent + l.deposit + l.maintenance; },
  coverPhoto(l){ return l.photos.length ? `images/${l.photos[0]}.jpg` : null; },
  byId(id){ return this.listings.find(l => l.id === id); },
};
