/* MakanMate shared listings data — mirrors Android SampleListings.kt */
const MM = {
  listings: [
    {
      id:"b", type:"flatmates", typeLabel:"Room in shared flat",
      title:"Room in 3 BHK with hill view",
      area:"Balewadi, Pune", address:"Flat 1904, Tower C, Sample Heights, Balewadi, Pune 411045",
      lat:18.5779, lng:73.7707,
      rent:14500, rentUnit:"/ room / month", deposit:29000, maintenance:1500,
      photos:["flat_b_6","flat_b_3","flat_b_5","flat_b_4","flat_b_1"],
      photoLabels:["Living room","Balcony view, 19th floor","Your room (AC)","Wardrobe","Kitchen"],
      safety:8.7, match:92, rating:4.6, reviewCount:11,
      busMin:35, scootyMin:22, cabMin:20,
      available:"1 Oct", hasTour:true,
      amenities:["Semi-furnished","Balcony, 19th floor","AC in your room","Shared kitchen","Wi-Fi included","Pool & gym","Lift, power backup"],
      rules:["Women only","Guests till 9 pm","Veg kitchen","No smoking indoors"],
      tags:["Women only","Veg kitchen","Pool & gym"],
      owner:{name:"Sneha Kulkarni",initials:"SK",replyTime:"~15 min",phone:"919876543210",since:"2024"},
      nearby:[{label:"Bus stop",dist:"400 m"},{label:"Grocery",dist:"300 m"},{label:"Hospital",dist:"1.8 km"},{label:"Gym",dist:"In society"}],
      reasons:[{good:true,text:"Within ₹15,000 budget"},{good:true,text:"Women only · 2 flatmates in IT"},{good:true,text:"Veg kitchen, Wi-Fi included"},{good:false,text:"35 min by bus at 9 am (22 min by scooty)"}],
      reviews:[
        {name:"Ananya",stay:"Stayed 14 months",stars:5,text:"Clean, safe society, and the owner fixes things fast. Bus stop is a 5-minute walk."},
        {name:"Mehak",stay:"Stayed 8 months",stars:4,text:"Great view and flatmates. Water pressure is low on the 19th floor in May."},
      ],
      flat:null,
    },
    {
      id:"e", type:"flat", typeLabel:"Whole flat",
      title:"2 BHK semi-furnished, high floor",
      area:"Tathawade, Pune", address:"Tower A, Sample Greens, Tathawade, Pune 411033",
      lat:18.6205, lng:73.7560,
      rent:24000, rentUnit:"/ month (whole flat)", deposit:72000, maintenance:2500,
      photos:["flat_e_2","flat_e_0","flat_e_1","flat_e_4","flat_e_5","flat_e_3"],
      photoLabels:["Living room, city view","Bedroom 1 (AC)","Bedroom 2","Kitchen","Bathroom 1","Bathroom 2"],
      safety:8.5, match:86, rating:4.5, reviewCount:6,
      busMin:30, scootyMin:18, cabMin:16,
      available:"1 Oct", hasTour:true,
      amenities:["2 bedrooms","AC in bedroom 1","TV unit","Modular kitchen","2 bathrooms","High floor","Lift, power backup"],
      rules:["Family or bachelors","Women sharing welcome","No loud parties after 10 pm"],
      tags:["2 BHK","Semi-furnished","2 bathrooms"],
      owner:{name:"Amol Deshpande",initials:"AD",replyTime:"~20 min",phone:"919876543211",since:"2024"},
      nearby:[{label:"Bus stop",dist:"500 m"},{label:"D-Mart",dist:"1.2 km"},{label:"Hospital",dist:"2 km"},{label:"Colleges",dist:"1.5 km"}],
      reasons:[{good:true,text:"₹12,000 each if 2 friends share"},{good:true,text:"2 bathrooms so sharing is easy"},{good:true,text:"AC in bedroom, high floor"},{good:false,text:"Semi-furnished: bring your own fridge"}],
      reviews:[
        {name:"Shruti",stay:"Stayed 11 months",stars:5,text:"Two of us shared it. Both bathrooms made mornings easy. Society is quiet."},
        {name:"Rohit",stay:"Stayed 1 year",stars:4,text:"Good flat; the approach road has traffic at 9 am."},
      ],
      flat:{bhk:"2 BHK",bedrooms:2,sqft:780,floor:"14th of 22",bathrooms:2,balconies:1,furnishing:"Semi-furnished",parking:"1 car",facing:"North",buildingAge:"5 years",allowed:["Family","Bachelors","Women sharing"],lockIn:"6 months",notice:"1 month",society:["Gym","Lifts","Power backup","Security 24×7","Garden"]},
    },
    {
      id:"c", type:"pg", typeLabel:"PG",
      title:"Sakhi Girls PG",
      area:"Wakad, Pune", address:"Near Bhumkar Chowk, Wakad, Pune 411057",
      lat:18.5987, lng:73.7626,
      rent:9500, rentUnit:"/ bed / month · twin sharing", deposit:19000, maintenance:0,
      photos:[], photoLabels:[],
      safety:9.1, match:85, rating:4.4, reviewCount:38,
      busMin:30, scootyMin:18, cabMin:16,
      available:"Now", hasTour:false,
      amenities:["3 veg meals a day","Laundry service","Wi-Fi","Daily cleaning","CCTV","Guard 24×7"],
      rules:["Women only","Visitors in the lobby","Meals 8 am, 1 pm, 8:30 pm"],
      tags:["Women only","Meals included","CCTV"],
      owner:{name:"Meera Joshi",initials:"MJ",replyTime:"~30 min",phone:"919876543212",since:"2022"},
      nearby:[{label:"Bus stop",dist:"200 m"},{label:"Grocery",dist:"150 m"},{label:"Hospital",dist:"1.2 km"},{label:"Cafés",dist:"Nearby"}],
      reasons:[{good:true,text:"₹5,500 under ₹15k budget"},{good:true,text:"3 veg meals a day included"},{good:true,text:"Women only · guard 24×7 · CCTV"},{good:false,text:"Shared room (2 beds)"}],
      reviews:[
        {name:"Sonal",stay:"Stayed 10 months",stars:5,text:"Food is like home and the warden is kind. Feels very safe."},
        {name:"Tanvi",stay:"Stayed 6 months",stars:4,text:"Good value. Rooms are small but clean."},
      ],
      flat:null,
    },
    {
      id:"f", type:"flat", typeLabel:"Whole flat",
      title:"1 BHK furnished with balcony",
      area:"Hinjewadi Phase 3, Pune", address:"Wing D, Sample Park, Maan, Hinjewadi Phase 3, Pune 411057",
      lat:18.5850, lng:73.7045,
      rent:17500, rentUnit:"/ month (whole flat)", deposit:52500, maintenance:1200,
      photos:["flat_f_0","flat_f_7","flat_f_1","flat_f_3","flat_f_4","flat_f_5","flat_f_6","flat_f_2"],
      photoLabels:["Living room","Bedroom","Bedroom window","Wardrobe","Balcony view","Feature wall","Bathroom","Bed with storage"],
      safety:8.1, match:83, rating:4.3, reviewCount:4,
      busMin:15, scootyMin:8, cabMin:8,
      available:"This week", hasTour:true,
      amenities:["Double bed","Wardrobe","TV unit","Balcony with hill view","Geyser","Kitchen","Fully furnished"],
      rules:["Working professionals","Women or couples preferred","No smoking indoors"],
      tags:["1 BHK","Fully furnished","Near IT park"],
      owner:{name:"Kavita Shinde",initials:"KS",replyTime:"~10 min",phone:"919876543213",since:"2025"},
      nearby:[{label:"IT park",dist:"1.5 km"},{label:"Bus stop",dist:"700 m"},{label:"Grocery",dist:"400 m"},{label:"Clinic",dist:"1 km"}],
      reasons:[{good:true,text:"Only 8 min by scooty to office"},{good:true,text:"Fully yours: no sharing"},{good:true,text:"Fully furnished, move in this week"},{good:false,text:"₹2,500 over ₹15k budget"}],
      reviews:[
        {name:"Pooja",stay:"Stayed 9 months",stars:4,text:"Walk-to-work convenience is unbeatable. Evenings are quiet; carry a torch on the back lane."},
      ],
      flat:{bhk:"1 BHK",bedrooms:1,sqft:620,floor:"9th of 14",bathrooms:1,balconies:1,furnishing:"Fully furnished",parking:"Bike",facing:"West",buildingAge:"2 years",allowed:["Working professionals","Couples","Women"],lockIn:"6 months",notice:"1 month",society:["Lifts","Power backup","Security 24×7","Sports court"]},
    },
    {
      id:"g", type:"flat", typeLabel:"Whole flat",
      title:"3 BHK fully furnished for sharing",
      area:"Baner, Pune", address:"Building 2, Sample Vista, Baner, Pune 411045",
      lat:18.5590, lng:73.7868,
      rent:42000, rentUnit:"/ month (whole flat)", deposit:126000, maintenance:3500,
      photos:["flat_g_4","flat_g_2","flat_g_5","flat_g_0","flat_g_3","flat_g_1","flat_g_6","flat_g_7"],
      photoLabels:["Living room & balcony","Living & dining","Sofa set","Bedroom 1","Bedroom 2","Bedroom 3","Wardrobe","Kitchen"],
      safety:8.9, match:81, rating:4.7, reviewCount:9,
      busMin:40, scootyMin:25, cabMin:22,
      available:"Now", hasTour:true,
      amenities:["5 single beds","Sofa set","Dining table","TV","2 balconies with greenery","Fridge","Washing machine"],
      rules:["Bachelors welcome","Company lease OK","Guests allowed"],
      tags:["3 BHK","Pool & gym","Bachelors OK"],
      owner:{name:"Nitin Gokhale",initials:"NG",replyTime:"~25 min",phone:"919876543214",since:"2023"},
      nearby:[{label:"Bus stop",dist:"300 m"},{label:"Cafés",dist:"Walkable"},{label:"Hospital",dist:"1 km"},{label:"Gyms",dist:"500 m"}],
      reasons:[{good:true,text:"₹14,000 each if 3 share"},{good:true,text:"Twin beds: easy to share with friends"},{good:true,text:"Big living room, 2 balconies"},{good:false,text:"40 min by bus at 9 am (25 min by scooty)"}],
      reviews:[
        {name:"Aditya",stay:"Stayed 2 years",stars:5,text:"Three of us shared it; the owner split the rent receipt for each person."},
        {name:"Megha",stay:"Stayed 1 year",stars:4,text:"Very spacious. Water tanker once in May."},
      ],
      flat:{bhk:"3 BHK",bedrooms:3,sqft:1350,floor:"6th of 12",bathrooms:3,balconies:2,furnishing:"Fully furnished",parking:"1 car + 2 bikes",facing:"East",buildingAge:"6 years",allowed:["Bachelors","Family","Company lease"],lockIn:"11 months",notice:"1 month",society:["Pool","Gym","Lifts","Power backup","Security 24×7","Visitor parking"]},
    },
    {
      id:"d", type:"studio", typeLabel:"Studio / 1 RK",
      title:"1 RK studio, furnished",
      area:"Wakad, Pune", address:"Kaspate Wasti, Wakad, Pune 411057",
      lat:18.5936, lng:73.7707,
      rent:12000, rentUnit:"/ month", deposit:36000, maintenance:800,
      photos:[], photoLabels:[],
      safety:8.2, match:80, rating:4.2, reviewCount:5,
      busMin:28, scootyMin:18, cabMin:15,
      available:"This week", hasTour:false,
      amenities:["Bed & wardrobe","Kitchenette","Wi-Fi ready","Attached bathroom"],
      rules:["Working professionals","No pets"],
      tags:["Solo living","Private","Budget-friendly"],
      owner:{name:"Vikram Pawar",initials:"VP",replyTime:"~1 hr",phone:"919876543215",since:"2025"},
      nearby:[{label:"Bus stop",dist:"600 m"},{label:"Grocery",dist:"200 m"},{label:"Clinic",dist:"500 m"},{label:"Tiffin",dist:"Nearby"}],
      reasons:[{good:true,text:"Private space, within budget"},{good:true,text:"18 min to office"},{good:false,text:"Deposit is 3 months rent"},{good:false,text:"Cooking on your own"}],
      reviews:[
        {name:"Neha",stay:"Stayed 12 months",stars:4,text:"Quiet lane, but the approach road is dark at night."},
      ],
      flat:null,
    },
    {
      id:"a", type:"flat", typeLabel:"Whole flat",
      title:"2 BHK premium flat",
      area:"Hinjewadi Phase 1, Pune", address:"Tower B, Sample Residency, Hinjewadi Phase 1, Pune 411057",
      lat:18.5913, lng:73.7389,
      rent:38000, rentUnit:"/ month (whole flat)", deposit:114000, maintenance:0,
      photos:["flat_a_6","flat_a_2","flat_a_4","flat_a_5","flat_a_3","flat_a_1","flat_a_7"],
      photoLabels:["Living & dining","Bedroom 1","Bedroom 2","Kitchen","Bathroom","Study nook","Entrance"],
      safety:8.4, match:74, rating:4.8, reviewCount:7,
      busMin:25, scootyMin:14, cabMin:12,
      available:"1 Oct", hasTour:true,
      amenities:["2 BHK fully furnished","Central AC","Modular kitchen","Glass shower","Smart lock","Smart TV","Fridge & washing machine"],
      rules:["Family or working professionals","Pets on request"],
      tags:["2 BHK","Central AC","Premium society"],
      owner:{name:"Ramesh Patil",initials:"RP",replyTime:"~12 min",phone:"919876543216",since:"2023"},
      nearby:[{label:"IT park",dist:"1 km"},{label:"Bus stop",dist:"300 m"},{label:"Hospital",dist:"2 km"},{label:"Mall",dist:"1.5 km"}],
      reasons:[{good:true,text:"Only 12 min to office"},{good:true,text:"Fully furnished, central AC"},{good:false,text:"Over budget alone; ₹19,000 each if 2 share"},{good:false,text:"Deposit is 3 months rent"}],
      reviews:[
        {name:"Karthik",stay:"Stayed 2 years",stars:5,text:"Premium society and very responsive owner. Walk to the IT park."},
      ],
      flat:{bhk:"2 BHK",bedrooms:2,sqft:1100,floor:"12th of 18",bathrooms:2,balconies:1,furnishing:"Fully furnished",parking:"1 car + 1 bike",facing:"East",buildingAge:"3 years",allowed:["Family","Working professionals"],lockIn:"11 months",notice:"1 month",society:["Pool","Gym","Lifts","Power backup","Security 24×7","Play area"]},
    },
  ],

  fmt(n){ return "₹" + n.toLocaleString("en-IN"); },
  moveIn(l){ return l.rent + l.deposit + l.maintenance; },
  coverPhoto(l){ return l.photos.length ? `images/${l.photos[0]}.jpg` : null; },
  byId(id){ return this.listings.find(l => l.id === id); },
};
